name: flash2
description: Perform merging of mate paired-end sequencing reads
keywords:
  - sort
  - reads merging
  - merge mate pairs
tools:
  - flash2:
      description: |
        Merge mates from fragments that are shorter than twice the read length
      homepage: https://github.com/dstreett/FLASH2
      documentation: {}
      doi: 10.1093/bioinformatics/btr507
      licence: ['GPL v3+']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 2; i.e., paired-end data.
      pattern: "*fastq.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: The merged fastq reads
      pattern: "*fastq.gz"
  - histogram:
      type: file
      description: Numeric histogram of merged read lengths
      pattern: "*.hist"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@Erkison"
  - "@vaofford"
