name: SeqPrep
description: Perform merging of mate paired-end sequencing reads and/or adapter trimming
keywords:
  - sort
  - reads merging
  - merge mate pairs
  - adapter trimming
tools:
  - seqprep:
      description: |
        Merge paired end Illumina reads that are overlapping into a single longer read or adapter trimming.
      homepage: https://github.com/jstjohn/SeqPrep
      documentation: {}
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FASTQ files of size 2; i.e., paired-end data.
      pattern: "*fastq.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: The merged fastq reads
      pattern: "*fastq.gz"

authors:
  - "@vaofford"
